/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Hastable;
import EDD.MonticuloBinario;
import Main.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class ImprimirDoc extends javax.swing.JFrame {
private static Hastable hash;
private static Cronometro c;
public static MonticuloBinario colita = new MonticuloBinario();
//private  static  MonticuloBinario colita;


    /**
     * Creates new form Usuario
     * @param hastable
     * @param crono
     * @param monticulo
     */
    public ImprimirDoc( Hastable hastable, Cronometro crono) {
        hash = hastable;
        c = crono;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreUser = new javax.swing.JTextField();
        Imprimir = new javax.swing.JButton();
        Cancelar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NombreDocumento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Imprimir Documento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 250, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nombre de usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel1.add(nombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 340, 30));

        Imprimir.setText("Imprimir");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 110, 50));

        Cancelar1.setText("Volver");
        Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 120, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Nombre del documento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        NombreDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(NombreDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 340, 30));

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                textAreaComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(textArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 470, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreDocumentoActionPerformed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar1ActionPerformed
        ColaImpresion v3 = new ColaImpresion(hash, c, colita);
        v3.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_Cancelar1ActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        if (hash.usuarioPresente(nombreUser.getText().toLowerCase())) {
            if (hash.documentoPresente(NombreDocumento.getText().toLowerCase(), nombreUser.getText().toLowerCase())) {

                if (hash.buscarDocumentoPorNombre(NombreDocumento.getText().toLowerCase()) != null) {
                    colita.insertarDoc(hash.buscarDocumentoPorNombre(NombreDocumento.getText().toLowerCase()));
                    
                    hash.eliminar_documento(nombreUser.getText().toLowerCase(), NombreDocumento.getText().toLowerCase());
                    textArea.setText(colita.imprimirTextArea());
                    JOptionPane.showMessageDialog(null, "El documento ha sido mandado a la cola de impresion!!! ");
                    colita.imprimir();
                    System.out.println("\n");
                    //colita = cola;
                   ColaImpresion v3 = new ColaImpresion(hash, c, colita);
//                   v3.setVisible(true);
//                   this.dispose();
                  //  hash.imprimir();
                } else {
                    JOptionPane.showMessageDialog(null, "El documento no se encuentra en la cola de impresion");
                }

            } else {
                JOptionPane.showMessageDialog(null, "El documento ingresado no se encuentra asignado a ningun usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El usuario no ha sido encontrado!!!");
        }
        
    }//GEN-LAST:event_ImprimirActionPerformed

    private void textAreaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_textAreaComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textAreaComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirDoc(hash, c).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar1;
    private javax.swing.JButton Imprimir;
    private javax.swing.JTextField NombreDocumento;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreUser;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
