/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Hastable;
import EDD.MonticuloBinario;

/**
 *
 * @author gabri
 */
public class Inicio extends javax.swing.JFrame {
private static Hastable hash;
private static Cronometro cronometro;
private static MonticuloBinario cola = new MonticuloBinario();
    /**
     * Creates new form Inicio
     * @param hastable
     * @param c
     * @param monticulo
     */
    public Inicio(Hastable hastable, Cronometro c, MonticuloBinario monticulo) {
        hash = hastable;
        cronometro = c;
        cola = monticulo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AgregarUser = new javax.swing.JButton();
        EliminarUser = new javax.swing.JButton();
        Cola = new javax.swing.JButton();
        AgregarDoc = new javax.swing.JButton();
        EliminarDoc1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("INICIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        AgregarUser.setText("Agregar usuario");
        AgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUserActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, 40));

        EliminarUser.setText("Eliminar usuario");
        EliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUserActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 160, 40));

        Cola.setText("Cola de impresion");
        Cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaActionPerformed(evt);
            }
        });
        jPanel1.add(Cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 160, 40));

        AgregarDoc.setText("Agregar Documento");
        AgregarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDocActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, 40));

        EliminarDoc1.setText("Eliminar Documento");
        EliminarDoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDoc1ActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUserActionPerformed
        Usuario v3 = new Usuario(hash, cronometro, cola);
        v3.setVisible(true);
        this.dispose();    }//GEN-LAST:event_AgregarUserActionPerformed

    private void EliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUserActionPerformed
        EliminarUser v3 = new EliminarUser(hash, cronometro, cola);
        v3.setVisible(true);
        this.dispose();    }//GEN-LAST:event_EliminarUserActionPerformed

    private void AgregarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDocActionPerformed
        AgregarDoc v3 = new AgregarDoc(hash, cronometro, cola);
        v3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarDocActionPerformed

    private void EliminarDoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDoc1ActionPerformed
        EliminarDoc v3 = new EliminarDoc(hash, cronometro, cola);
        v3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarDoc1ActionPerformed

    private void ColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaActionPerformed
        ColaImpresion v3 = new ColaImpresion(hash, cronometro, cola);
        v3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ColaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio(hash, cronometro, cola).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDoc;
    private javax.swing.JButton AgregarUser;
    private javax.swing.JButton Cola;
    private javax.swing.JButton EliminarDoc1;
    private javax.swing.JButton EliminarUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
